In [1]:
import json
import numpy as np
filename = 'eatStuff'

In [2]:
with open('../agar.io-clone/bin/' + filename) as json_data:
    data = json.load(json_data,) 

In [3]:
answers = np.ones((len(data), 2))
food = np.ones((len(data), 50, 2))
virus = np.ones((len(data), 10, 2))

In [4]:

for i in range(len(data)):
    answers[i][0] = data[i]['x']
    answers[i][1] = data[i]['y']
    k = 0
    while k < len(data[i]['food'][filename]) or k < 50:
        if (k < len(data[i]['food'][filename])):
            food[i][k][0] = data[i]['food'][filename][k]['x']
            food[i][k][1] = data[i]['food'][filename][k]['y']
        else:
            food[i][k][0] = 0
            food[i][k][1] = 0
        k += 1
    k = 0
    while k < len(data[i]['virus'][filename]) or k < 10:
        if (k < len(data[i]['virus'][filename])):
            virus[i][k][0] = data[i]['virus'][filename][k]['x']
            virus[i][k][1] = data[i]['virus'][filename][k]['y']
        else:
            virus[i][k][0] = 0
            virus[i][k][1] = 0
        k += 1
    answers[i][1] = data[i]['y']
    #if (i == 12):
        #print(data[i])

In [5]:
virus[8]

array([[ 725.        , 3533.        ],
       [1288.49827584, 2863.49827584],
       [ 202.29925373, 3555.29925373],
       [ 628.74613392, 3282.74613392],
       [1120.45227269, 3004.45227269],
       [1400.14690015, 3174.14690015],
       [   0.        ,    0.        ],
       [   0.        ,    0.        ],
       [   0.        ,    0.        ],
       [   0.        ,    0.        ]])

In [6]:
food[3]

array([[1485., 3023.],
       [ 802., 3542.],
       [1015., 2924.],
       [1365., 3627.],
       [1280., 3103.],
       [ 906., 3604.],
       [ 781., 3630.],
       [1334., 3437.],
       [ 735., 3291.],
       [1767., 3411.],
       [1408., 3277.],
       [1203., 2934.],
       [1153., 3008.],
       [1595., 3557.],
       [1156., 3088.],
       [1492., 3423.],
       [1573., 3588.],
       [1748., 3493.],
       [1562., 3479.],
       [1431., 2907.],
       [ 396., 2976.],
       [ 678., 3268.],
       [1092., 3435.],
       [1069., 2920.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   0.,    0.],
       [   

In [7]:
class NeuralNetwork:
    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.hidden_size = 10
        self.W1 = np.random.rand(x.shape[0], self.hidden_size) - 0.5
        self.b1 = np.random.rand(x.shape[0])
        self.W2 = np.random.rand(self.hidden_size, y.shape[0])
        self.b1 = np.random.rand(self.hidden_size)
        prev_val = [0, 0]
    
    def train(self, data, out):
        return 0

In [19]:
class NeuralNetworkLayer:
    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.hidden_size = 10
        self.W1 = np.random.rand(x.shape[0] + 2, y.shape[0]) - 0.5
        #self.W1 = np.random.rand(x.shape[0], 1) - 0.5
        self.b1 = np.random.rand(x.shape[0] + 2) - 0.5
        self.lr = .0001
        self.prev_val = [0, 0]
    
    def train(self, data, out):
        data = np.append(data, self.prev_val)
        res = np.matmul(data + self.b1, self.W1)
        self.prev_val = res
        loss = out - res
        self.W1 += self.W1 * loss * self.lr
        return loss
    #
    def test(self, data, out):
        return 1

In [20]:
x = np.ones((len(data), 120))
for i in range(len(data)):
    concat_val = np.concatenate((food[i], virus[i]), axis=0)
    x[i] = concat_val.flatten()

In [30]:
network = NeuralNetworkLayer(x[0], answers[0])

In [31]:
network.train(x[0], answers[0][1])

array([-6841.98000655, -1187.83593796])

In [32]:
loss = 0
for i in range(len(data)):
    #print(answers[i][0])
    loss = network.train(x[i], answers[i][1])
    print(loss)
print('epoch 1')
print(loss)

[-2067.61955091 -1243.9962392 ]
[-1352.15881068  -559.55305107]
[-1168.16443677  -649.21931527]
[-975.40854873 -542.66453204]
[-848.89587998 -506.62186579]
[-745.94502288 -462.23242016]
[-664.33527362 -427.52190236]
[-596.94881828 -396.27068294]
[-540.53332774 -368.81541508]
[-492.52025532 -344.25659821]
[-451.1569042  -322.18081779]
[-415.14169464 -302.20675964]
[-383.50010319 -284.04382602]
[-355.48379665 -267.45398089]
[-330.50846406 -252.24201437]
[-308.11059043 -238.24527118]
[-287.91746404 -225.32685765]
[-269.62574439 -213.3704631 ]
[-252.98587921 -202.27645894]
[-237.79057258 -191.95888744]
[-223.86612002 -182.34310708]
[-211.06580696 -173.36392654]
[-199.26481603 -164.96410908]
[-188.35625341 -157.09316127]
[-178.24801582 -149.70634317]
[-168.8602968  -142.76385262]
[-160.1235842  -136.23014799]
[-151.97703903 -130.07338197]
[-144.36717323 -124.26492531]
[-629.2467635 -610.7789638]
[-575.2764394  -559.18560081]
[-531.20387719 -518.58450056]
[-495.40137713 -485.3161825 ]
[-467.

[-286.54298148 -286.31093594]
[-296.66090308 -296.605865  ]
[-300.74317656 -300.85425622]
[-301.9202524  -302.18571904]
[-297.24803363 -297.65337931]
[-291.83048833 -292.36124882]
[-286.6674629  -287.30790976]
[-284.74157125 -285.47752571]
[-284.98659831 -285.80532418]
[-282.3609054 -283.2520846]
[-277.90700882 -278.86230343]
[-273.64567678 -274.65664741]
[-269.56474498 -270.62325812]
[-265.65326093 -266.75214871]
[-261.90113449 -263.03404938]
[-258.29906322 -259.4603806 ]
[-254.83845644 -256.02318887]
[-251.51136819 -252.71509089]
[-248.31043779 -249.52922349]
[-245.22883669 -246.45919881]
[-242.26022117 -243.49906397]
[-239.39868992 -240.64326478]
[-236.63874606 -237.88661302]
[-233.97526297 -235.22425688]
[-230.40345355 -231.65165419]
[-224.92963413 -226.17546874]
[-218.56979856 -219.8119755 ]
[-208.32782759 -209.56505519]
[-196.2373822  -197.46893844]
[-175.30900601 -176.53401935]
[-150.62022203 -151.8389035 ]
[-126.19473847 -127.40675263]
[-112.01838553 -113.22315088]
[-94.9869372

[120.77612422 120.33701347]
[120.48990961 120.0475652 ]
[112.20093216 111.75537005]
[92.9286209  92.48021386]
[59.70059271 59.25013991]
[41.55279955 41.10163493]
[28.4493056  27.99795567]
[14.378156   13.92705309]
[1.34211593 0.89177772]
[-7.66122088 -8.11033805]
[-17.64194264 -18.08955962]
[-23.59761186 -24.04337199]
[-30.5384409  -30.98218188]
[-35.46204769 -35.90352846]
[-41.37361698 -41.81269915]
[-44.270809   -44.70729454]
[-49.16126571 -49.59510127]
[-52.04015387 -52.47117302]
[-55.91258499 -56.34072975]
[-59.77623278 -60.2013857 ]
[-61.63127239 -62.05332793]
[-66.48271064 -66.90165044]
[-70.32343225 -70.73909538]
[-73.15607344 -73.56837073]
[-77.98319808 -78.39207552]
[-82.80025624 -83.20557127]
[-90.60752637 -91.00915712]
[-92.39836018 -92.79606767]
[-95.18700381 -95.58081935]
[-97.97127382 -98.36114132]
[ -99.75134301 -100.13721662]
[-101.52960803 -101.91148245]
[-101.30616694 -101.6840302 ]
[-101.08548108 -101.459398  ]
[-100.86750224 -101.23752204]
[-100.65218775 -101.018358

[-204.50008986 -204.50009153]
[-204.50008802 -204.50008966]
[-204.50008622 -204.50008783]
[-203.50008445 -203.50008603]
[-203.50008274 -203.50008428]
[-201.50008105 -201.50008256]
[-201.50007942 -201.5000809 ]
[-201.50007782 -201.50007927]
[-200.50007625 -200.50007767]
[-200.50007472 -200.50007612]
[-200.50007322 -200.50007459]
[-199.50007176 -199.50007309]
[-199.50007032 -199.50007164]
[-199.50006892 -199.50007021]
[-197.50006755 -197.50006881]
[-197.50006621 -197.50006745]
[-196.5000649  -196.50006611]
[-193.50006363 -193.50006482]
[-187.5000624  -187.50006356]
[-182.50006123 -182.50006237]
[-177.50006011 -177.50006123]
[-173.50005904 -173.50006014]
[-170.50005802 -170.5000591 ]
[-169.50005703 -169.50005809]
[-168.50005606 -168.50005711]
[-167.50005512 -167.50005615]
[-167.5000542  -167.50005521]
[-167.50005329 -167.50005428]
[-167.50005239 -167.50005337]
[-167.50005152 -167.50005248]
[-167.50005065 -167.5000516 ]
[-167.50004981 -167.50005073]
[-167.50004897 -167.50004988]
[-167.5000

In [33]:
import matplotlib.pyplot as plt
plt.plot(answers[:, 0])
plt.ylabel('some numbers')
plt.show()

<Figure size 640x480 with 1 Axes>

In [35]:
network = NeuralNetworkLayer(x[0], answers[0])
loss = 0
for i in range(len(data)):
    #print(answers[i][0])
    loss = network.train(x[i], answers[i])
    print(loss)
print('epoch 1')
print(loss)

[-1252.00089107 -2210.15686823]
[-470.99685662 -681.65185041]
[ -662.04615593 -1032.60113688]
[-512.80652763 -799.53767522]
[-484.16993344 -766.7740607 ]
[-429.40157068 -689.93954475]
[-389.73103577 -635.70029084]
[-352.70306811 -584.67569923]
[-320.49324041 -540.2717019 ]
[-291.77771531 -500.56572658]
[-266.20868511 -465.07857623]
[-243.32980295 -433.17373303]
[-222.79650586 -404.37528211]
[-204.31165868 -378.2761193 ]
[-187.62542797 -354.5368057 ]
[-172.52493939 -332.87052937]
[-158.82809217 -313.03394109]
[-146.37823559 -294.81936028]
[-135.03995664 -278.0486322 ]
[-124.6956564  -262.56816901]
[-115.24276224 -248.24493866]
[-106.59144186 -234.96319894]
[ -98.66271862 -222.62182376]
[ -91.38690901 -211.13210242]
[ -84.70232055 -200.41591856]
[ -78.55416125 -190.40423587]
[ -72.893622  -181.0358327]
[ -67.67710084 -172.25623986]
[ -62.86554436 -164.01684492]
[-869.4238863  -648.27413382]
[-830.48317893 -592.72416015]
[-793.33562918 -552.98856528]
[-748.94724807 -519.5846384 ]
[-707.89

[-35.30692792  64.93575986]
[-37.30581851  63.57794163]
[-39.30465235  62.24016762]
[-43.30343012  62.92249049]
[-46.30209185  62.58163714]
[-49.30066846  61.24029644]
[-53.29916163  60.92011444]
[-56.29754312  60.59868606]
[-58.29584414  60.27649314]
[-59.29409573  59.95362613]
[-61.29232828  58.63018099]
[-61.29051304  57.328837  ]
[-61.28870951  56.04916971]
[-61.28691761  54.79114695]
[-61.28513726  53.55471184]
[-61.28336838  52.33979269]
[-61.28161089  51.14630353]
[-61.27986471  49.97414461]
[-61.27812978  48.8232031 ]
[-61.276406    47.69335365]
[-59.27469331  46.58445899]
[-57.27304656  45.49637054]
[-55.27146468  44.42893095]
[-52.26994663  43.3819707 ]
[-49.26851843  40.35531082]
[-42.2671787   36.39718944]
[-37.26603382  34.53021659]
[-31.26502836  30.70399648]
[-28.2641864   28.96787614]
[-23.26342783  26.27047447]
[-16.26280379  21.63677782]
[-7.26236622 16.11463145]
[2.7378327  5.72587389]
[20.73776717 -8.40862257]
[ 39.73722553 -27.19761108]
[ 56.73617793 -46.52790644]


[-258.83914329 -210.3339791 ]
[-249.55397653 -215.31660055]
[-243.34671907 -219.29916642]
[-238.19861212 -222.2817774 ]
[-229.10193883 -227.26452701]
[-227.07216614 -228.2472707 ]
[-226.07464425 -228.2303234 ]
[-225.10389856 -228.21375835]
[-224.15903706 -228.1975675 ]
[-223.23919262 -228.18174247]
[-221.34353519 -228.16627511]
[-217.47520439 -228.15115742]
[-213.64084765 -228.1363812 ]
[-209.83892731 -228.12193818]
[-197.06801328 -228.10782099]
[-190.35921712 -228.09402244]
[-183.68791748 -228.08053276]
[-175.05241263 -228.06734714]
[-168.45787132 -228.05445888]
[-162.89567793 -228.04186092]
[-159.36115327 -228.02954741]
[-158.84668884 -228.0175123 ]
[-156.34199587 -228.00574987]
[-153.85312937 -227.99425468]
[-147.37953226 -227.98302022]
[-139.93283873 -227.97204062]
[-130.5149466  -227.96130933]
[-122.1306257  -227.95082062]
[-112.77566409 -227.94056874]
[-100.45188761 -227.93054862]
[ -89.16675507 -227.92075494]
[ -80.91618945 -227.91118216]
[ -72.6908166  -227.90182558]
[ -63.4899